// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250722122435_InitalSetup")]
    partial class InitalSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-fidelity gaming headset with surround sound. Immerse yourself in the game with crystal-clear audio and comfortable earcups. Features include noise-cancelling microphone and customizable RGB lighting.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Headset",
                            Name = "Gaming Headset",
                            Price = 79.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "RGB mechanical keyboard with tactile switches. Experience responsive and satisfying keystrokes. Built with durable materials and programmable macros for ultimate gaming performance.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 129.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ergonomic wireless mouse with customizable DPI. Enjoy lag-free gaming with precise tracking and a comfortable grip. Long-lasting battery life and multiple programmable buttons.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Mouse",
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "27-inch curved gaming monitor with 144Hz refresh rate. Immerse yourself in stunning visuals and smooth gameplay. High resolution and wide viewing angles for an expansive experience.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Monitor",
                            Name = "Curved Gaming Monitor",
                            Price = 299.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Description = "Full HD 1080p webcam with autofocus. Perfect for streaming, video calls, and online meetings. Built-in microphone with noise reduction.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Webcam",
                            Name = "Webcam 1080p",
                            Price = 59.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ergonomic gaming chair with lumbar support. Designed for long gaming sessions, providing maximum comfort and adjustability. High-quality PU leather and robust construction.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=Chair",
                            Name = "Gaming Chair",
                            Price = 199.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            Description = "Portable 1TB SSD for blazing-fast data transfer. Ideal for gamers and content creators needing extra storage and speed. Compact and durable design.",
                            ImageUrl = "https://placehold.co/400x300/3f3f3f/ffffff?text=SSD",
                            Name = "External SSD 1TB",
                            Price = 99.99m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
